### PR TITLE
CI: migrate from Travis-CI to GitHub Actions

### PR DESCRIPTION
**Pull request by kenhys**

### CODE REVIEW

**Review by cosmo0920 — CHANGES_REQUESTED** [review]
This couldn't work correctly.
Please be careful directory structure.
`.github/.github/...` is useless.

**Comment by cosmo0920** [comment]
Test cases seems not to be working on Windows.
Could you take a look?

**Comment by kenhys** [comment]
The unexpectedly nested directory structure is fixed.

**Comment by kenhys** [comment]
On my sid environment, ruby 2.5 test case succeeds, I'll check them.

**Comment by kenhys** [comment]
ruby 2.5 on linux test case was fixed.

**Comment by kenhys** [comment]
On windows, `accept': stream closed in another thread (IOError)` causes this failure.


```
2021-01-18T05:17:15.9154812Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:240: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
2021-01-18T05:17:15.9156268Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:22: warning: The called method `config' is defined here
2021-01-18T05:17:15.9297282Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/cool.io-1.7.0/lib/cool.io/io.rb:113: warning: instance variable @_io not initialized
2021-01-18T05:17:15.9377756Z D:/a/fluent-plugin-irc/fluent-plugin-irc/lib/fluent/plugin/out_irc.rb:230: warning: instance variable @joined not initialized
2021-01-18T05:17:15.9379247Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/cool.io-1.7.0/lib/cool.io/io.rb:174: warning: instance variable @_write_watcher not initialized
2021-01-18T05:17:15.9380532Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/cool.io-1.7.0/lib/cool.io/io.rb:113: warning: instance variable @_io not initialized
2021-01-18T05:17:16.4514308Z #<Thread:0x00000000085decf8 D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:242 run> terminated with exception (report_on_exception is true):
2021-01-18T05:17:16.4515294Z ===============================================================================
2021-01-18T05:17:16.4516681Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:243:in `accept': stream closed in another thread (IOError)
2021-01-18T05:17:16.4517453Z E
2021-01-18T05:17:16.4518453Z 	from D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:243:in `block (2 levels) in emit_test'
2021-01-18T05:17:16.4519216Z ===============================================================================
2021-01-18T05:17:16.4528758Z Error: test_emit(IRCOutputTest): NoMethodError: undefined method `[]' for nil:NilClass
2021-01-18T05:17:16.4530034Z D:/a/fluent-plugin-irc/fluent-plugin-irc/lib/fluent/plugin/out_irc.rb:230:in `joined?'
2021-01-18T05:17:16.4531169Z D:/a/fluent-plugin-irc/fluent-plugin-irc/lib/fluent/plugin/out_irc.rb:242:in `send_message'
2021-01-18T05:17:16.4532315Z D:/a/fluent-plugin-irc/fluent-plugin-irc/lib/fluent/plugin/out_irc.rb:123:in `on_timer'
2021-01-18T05:17:16.4533474Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:251:in `block (3 levels) in emit_test'
2021-01-18T05:17:16.4534645Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:249:in `each'
2021-01-18T05:17:16.4535807Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:249:in `block (2 levels) in emit_test'
2021-01-18T05:17:16.4537352Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0-x64-mingw32/lib/fluent/test/driver/base.rb:198:in `block in run_actual'
2021-01-18T05:17:16.4548056Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
2021-01-18T05:17:16.4549103Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
2021-01-18T05:17:16.4550044Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/2.7.0/timeout.rb:33:in `catch'
2021-01-18T05:17:16.4550935Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/2.7.0/timeout.rb:33:in `catch'
2021-01-18T05:17:16.4551857Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
2021-01-18T05:17:16.4553029Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0-x64-mingw32/lib/fluent/test/driver/base.rb:197:in `run_actual'
2021-01-18T05:17:16.4554883Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0-x64-mingw32/lib/fluent/test/driver/output.rb:50:in `run_actual'
2021-01-18T05:17:16.4556154Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0-x64-mingw32/lib/fluent/test/driver/base.rb:95:in `run'
2021-01-18T05:17:16.4557386Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0-x64-mingw32/lib/fluent/test/driver/base_owner.rb:130:in `run'
2021-01-18T05:17:16.4559279Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0-x64-mingw32/lib/fluent/test/driver/event_feeder.rb:39:in `run'
2021-01-18T05:17:16.4576530Z C:/hostedtoolcache/windows/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/gems/fluentd-1.12.0-x64-mingw32/lib/fluent/test/driver/output.rb:43:in `run'
2021-01-18T05:17:16.4577730Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:248:in `block in emit_test'
2021-01-18T05:17:16.4578923Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:238:in `open'
2021-01-18T05:17:16.4579915Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:238:in `emit_test'
2021-01-18T05:17:16.4580894Z D:/a/fluent-plugin-irc/fluent-plugin-irc/test/plugin/test_out_irc.rb:103:in `test_emit'
2021-01-18T05:17:16.4582469Z      100:     body = MESSAGE % [TAG, Time.at(Fluent::Engine.now).strftime(TIME_FORMAT), msg]
```

**Comment by kenhys** [comment]
It seems that cool.io TCPSocket#connect behavior is different. On windows it reaches precreate, but not for linux.

**Comment by kenhys** [comment]
> It seems that cool.io TCPSocket#connect behavior is different. On windows it reaches precreate, but not for linux.

This situation is caused by `Coolio::DNSResolver.hosts`.

**Comment by kenhys** [comment]
I've send PR to cool.io to resolve issue.
https://github.com/tarcieri/cool.io/pull/71

**Comment by cosmo0920** [comment]
Hmm.., with [patched cool.io 1.7.0](https://github.com/tarcieri/cool.io/pull/71), this plugin's test cases still stuck.... :<

```
  test_emit:                                                                                            C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:46: warning: assigned but unused variable - csv_arguments
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/helper.rb:49: warning: character class has duplicated range: /^[#|&|+|!][a-zA-Z0-9]+/
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:46: warning: method redefined; discarding old channels
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:50: warning: method redefined; discarding old channels=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of channels= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:54: warning: method redefined; discarding old keys
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:58: warning: method redefined; discarding old keys=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of keys= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:46: warning: method redefined; discarding old channels
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:50: warning: method redefined; discarding old channels=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of channels= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:54: warning: method redefined; discarding old users
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:58: warning: method redefined; discarding old users=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of users= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:39: warning: method redefined; discarding old channels
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:43: warning: method redefined; discarding old channels=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of channels= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:39: warning: method redefined; discarding old channels
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:43: warning: method redefined; discarding old channels=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of channels= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:39: warning: method redefined; discarding old channels
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:43: warning: method redefined; discarding old channels=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of channels= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/commands.rb:35: warning: method redefined; discarding old initialize
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:3: warning: previous definition of initialize was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/commands.rb:169: warning: method redefined; discarding old hopcount
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/commands.rb:231: warning: method redefined; discarding old initialize
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:3: warning: previous definition of initialize was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/commands.rb:242: warning: method redefined; discarding old count
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/commands.rb:248: warning: method redefined; discarding old initialize
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:3: warning: previous definition of initialize was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:39: warning: method redefined; discarding old nicks
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:43: warning: method redefined; discarding old nicks=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of nicks= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/commands.rb:264: warning: method redefined; discarding old initialize
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:3: warning: previous definition of initialize was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:39: warning: method redefined; discarding old nicks
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:43: warning: method redefined; discarding old nicks=
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages.rb:52: warning: previous definition of nicks= was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/commands.rb:270: warning: method redefined; discarding old initialize
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:3: warning: previous definition of initialize was here
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/messages/replies.rb:145: warning: method redefined; discarding old initialize
C:/Users/cosmo/Documents/GitHub/fluent-plugin-irc/vendor/bundle/ruby/2.6.0/gems/irc_parser-0.1.2/lib/irc_parser/factory.erb:3: warning: previous definition of initialize was here
```

**Comment by kenhys** [comment]
I'll investigate it.

**Comment by kenhys** [comment]
Hmm, It seems that `s = serv.accept` will be blocked.

https://github.com/fluent-plugins-nursery/fluent-plugin-irc/blob/master/test/plugin/test_out_irc.rb#L242

**Comment by kenhys** [comment]
`Coolio::DNSResolver.hosts` should consider dual-stack (IPv4 and IPv6),  it seems that `TCPServer.accept` assumes `AF_INET6`  , so it will be stuck if `localhost` is resolved as `127.0.0.1`.

**Comment by kenhys** [comment]
I've changed the default behavior of https://github.com/tarcieri/cool.io/pull/71.

**Comment by kenhys** [comment]
I've updated PR. https://github.com/tarcieri/cool.io/pull/71 again.

**Comment by kenhys** [comment]
https://github.com/tarcieri/cool.io/pull/71 was merged.

**Comment by kenhys** [comment]
With the latest cool.io 1.7.1, it still fails...

**Comment by kenhys** [comment]
Got it. the edge case is not considered.

**Comment by kenhys** [comment]
I've send https://github.com/tarcieri/cool.io/pull/73 again. orz...

**Comment by cosmo0920** [comment]
I'd confirmed that `test_emit` can pass with https://github.com/tarcieri/cool.io/pull/73.

**Review by cosmo0920 — APPROVED** [review]

**Comment by cosmo0920** [comment]
CI failure is not this plugin test's issue. I'll merge this PR.

**Pull request merged**
