### PR TITLE
Migrate to use v0.14 API

### PR DESCRIPTION
**Pull request by cosmo0920**
This PR is naive implementation to use v0.14 API and still has room for improvement.
Should this plugin to be buffered or asynchronous buffered plugin in v0.14?

### CODE REVIEW

**Comment by cosmo0920** [comment]
Hmm, socket outputs order seems to be nondeterministic...
We should investigate for it. :confounded:

**Comment by choplin** [comment]
寿司ゆき:thanks

**Comment by choplin** [comment]
First, I'm afraid that I do not use this plugin actively any longer, or even fluentd itself. So, If you want, I will transfer the ownership of github and gem repository to you or your team.
 
> Should this plugin to be buffered or asynchronous buffered plugin in v0.14?

It's OK. Actually, `@send_queue` and `timer` play the similar role to what BufferedPlugin does. I do not remember why I choose OutputPlugin as a base class. (I suppose that I woud like originally to send messages to IRC immediately by bypassing buffer. But this idea has came to nothing now becuase the plugin bufferes events in `@send_queue`... )

> Hmm, socket outputs order seems to be non-deterministic...

Sorry, I don't get the meaning of the comment. What is the problem? Generally speaking, I think that messages sent to tcp socket should be ordered.

**Comment by cosmo0920** [comment]
> First, I'm afraid that I do not use this plugin actively any longer, or even fluentd itself. So, If you want, I > will transfer the ownership of github and gem repository to you or your team.

OK. I'll discuss about it with @okkez and decide whether or not to continue maintenance in @fluent-plugins-nursery. 

>> Hmm, socket outputs order seems to be non-deterministic...
> 
> Sorry, I don't get the meaning of the comment. What is the problem? Generally speaking, I think that messages sent to tcp socket should be ordered.

I means that non-deterministic case occurring in test cases.
This behavior causes test failure in Travis CI.

**Comment by choplin** [comment]
Thank you. I will check the result of travis later.

**Comment by cosmo0920** [comment]
@okkez and I discussed about maintaining this plugin. 
We decide to accept to take over this plugin.
Could you create `fluent-plugin-irc` taking over issue in https://github.com/fluent-plugins-nursery/contact like as https://github.com/fluent-plugins-nursery/contact/issues/1?

**Comment by choplin** [comment]
done https://github.com/fluent-plugins-nursery/contact/issues/2

**Comment by cosmo0920** [comment]
Can we merge this PR?
Or additional work such as stabilizing test cases is required?

**Comment by okkez** [comment]
Go ahead 🚆 
After merge this PR, could you fix test?

**Comment by cosmo0920** [comment]
Sure, I'll do, or I'll converting buffered plugin.

**Pull request merged**
